export const CUISINES = [
  {
    title: 'Afghan',
    value: 'afghan',
    source: require('../assets/images/cuisines/afghan.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'African',
    value: 'african',
    source: require('../assets/images/cuisines/african.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'American',
    value: 'american',
    source: require('../assets/images/cuisines/american.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Arab',
    value: 'arab',
    source: require('../assets/images/cuisines/arab.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Asian',
    value: 'asian',
    source: require('../assets/images/cuisines/asian.jpg'),
  },
  {
    title: 'Bangladeshi',
    value: 'bangladeshi',
    source: require('../assets/images/cuisines/bangladeshi.jpg'),
  },
  {
    title: 'Bar & Grill',
    value: 'bar-and-grill',
    source: require('../assets/images/cuisines/bar-and-grill.jpg'),
  },
  {
    title: 'Barbeque',
    value: 'barbeque',
    source: require('../assets/images/cuisines/barbeque.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Brazilian',
    value: 'brazilian',
    source: require('../assets/images/cuisines/brazilian.jpg'),
  },
  {
    title: 'Breakfast',
    value: 'breakfast',
    source: require('../assets/images/cuisines/breakfast.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'British',
    value: 'british',
    source: require('../assets/images/cuisines/british.jpg'),
  },
  {
    title: 'Brunch',
    value: 'brunch',
    source: require('../assets/images/cuisines/brunch.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Burgers',
    value: 'burgers',
    source: require('../assets/images/cuisines/burgers.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Cafe',
    value: 'cafe',
    source: require('../assets/images/cuisines/cafe.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Caribbean',
    value: 'caribbean',
    source: require('../assets/images/cuisines/caribbean.jpg'),
  },
  {
    title: 'Chicken',
    value: 'chicken',
    source: require('../assets/images/cuisines/chicken.jpg'),
  },
  {
    title: 'Chicken & Waffles',
    value: 'chicken-and-waffles',
    source: require('../assets/images/cuisines/chicken-and-waffles.jpg'),
  },
  {
    title: 'Chinese',
    value: 'chinese',
    source: require('../assets/images/cuisines/chinese.jpg'),
  },
  {
    title: 'Dessert',
    value: 'dessert',
    source: require('../assets/images/cuisines/dessert.jpg'),
  },
  {
    title: 'East African',
    value: 'east-african',
    source: require('../assets/images/cuisines/east-african.jpg'),
  },
  {
    title: 'Egyptian',
    value: 'egyptian',
    source: require('../assets/images/cuisines/egyptian.jpg'),
  },
  {
    title: 'Emirati',
    value: 'emirati',
    source: require('../assets/images/cuisines/emirati.jpg'),
  },
  {
    title: 'English',
    value: 'english',
    source: require('../assets/images/cuisines/english.jpg'),
  },
  {
    title: 'Eritrean',
    value: 'eritrean',
    source: require('../assets/images/cuisines/eritrean.jpg'),
  },
  {
    title: 'Ethiopian',
    value: 'ethiopian',
    source: require('../assets/images/cuisines/ethiopian.jpg'),
  },
  {
    title: 'European',
    value: 'european',
    source: require('../assets/images/cuisines/european.jpg'),
  },
  {
    title: 'Fast Food',
    value: 'fast-food',
    source: require('../assets/images/cuisines/fast-food.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'French',
    value: 'french',
    source: require('../assets/images/cuisines/french.jpg'),
  },
  {
    title: 'Fried Chicken',
    value: 'fried-chicken',
    source: require('../assets/images/cuisines/fried-chicken.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Greek',
    value: 'greek',
    source: require('../assets/images/cuisines/greek.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Hawaiian',
    value: 'hawaiian',
    source: require('../assets/images/cuisines/hawaiian.jpg'),
  },
  {
    title: 'Healthy',
    value: 'healthy',
    source: require('../assets/images/cuisines/healthy.jpg'),
  },
  {
    title: 'Indian',
    value: 'indian',
    source: require('../assets/images/cuisines/indian.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Indo-Chinese',
    value: 'indo-chinese',
    source: require('../assets/images/cuisines/indo-chinese.jpg'),
  },
  {
    title: 'Indonesian',
    value: 'indonesian',
    source: require('../assets/images/cuisines/indonesian.jpg'),
  },
  {
    title: 'International',
    value: 'international',
    source: require('../assets/images/cuisines/international.jpg'),
  },
  {
    title: 'Iraqi',
    value: 'iraqi',
    source: require('../assets/images/cuisines/iraqi.jpg'),
  },
  {
    title: 'Italian',
    value: 'italian',
    source: require('../assets/images/cuisines/italian.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Japanese',
    value: 'japanese',
    source: require('../assets/images/cuisines/japanese.jpg'),
  },
  {
    title: 'Kazakh',
    value: 'kazakh',
    source: require('../assets/images/cuisines/kazakh.jpg'),
  },
  {
    title: 'Kebab',
    value: 'kebab',
    source: require('../assets/images/cuisines/kebab.jpg'),
  },
  {
    title: 'Kenyan',
    value: 'kenyan',
    source: require('../assets/images/cuisines/kenyan.jpg'),
  },
  {
    title: 'Korean',
    value: 'korean',
    source: require('../assets/images/cuisines/korean.jpg'),
  },
  {
    title: 'Kyrgyz',
    value: 'kyrgyz',
    source: require('../assets/images/cuisines/kyrgyz.jpg'),
  },
  {
    title: 'Latin American',
    value: 'latin-american',
    source: require('../assets/images/cuisines/latin-american.jpg'),
  },
  {
    title: 'Lebanese',
    value: 'lebanese',
    source: require('../assets/images/cuisines/lebanese.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Malaysian',
    value: 'malaysian',
    source: require('../assets/images/cuisines/malaysian.jpg'),
  },
  {
    title: 'Mediterranean',
    value: 'mediterranean',
    source: require('../assets/images/cuisines/mediterranean.jpg'),
  },
  {
    title: 'Mexican',
    value: 'mexican',
    source: require('../assets/images/cuisines/mexican.jpg'),
  },
  {
    title: 'Moroccan',
    value: 'moroccan',
    source: require('../assets/images/cuisines/moroccan.jpg'),
  },
  {
    title: 'Nepalese',
    value: 'nepalese',
    source: require('../assets/images/cuisines/nepalese.jpg'),
  },
  {
    title: 'Noodles',
    value: 'noodles',
    source: require('../assets/images/cuisines/noodles.jpg'),
  },
  {
    title: 'Pakistani',
    value: 'pakistani',
    source: require('../assets/images/cuisines/pakistani.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Palestinian',
    value: 'palestinian',
    source: require('../assets/images/cuisines/palestinian.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Pan Asian',
    value: 'pan-asian',
    source: require('../assets/images/cuisines/pan-asian.jpg'),
  },
  {
    title: 'Pasta',
    value: 'pasta',
    source: require('../assets/images/cuisines/pasta.jpg'),
  },
  {
    title: 'Persian',
    value: 'persian',
    source: require('../assets/images/cuisines/persian.jpg'),
  },
  {
    title: 'Pies',
    value: 'pies',
    source: require('../assets/images/cuisines/pies.jpg'),
  },
  {
    title: 'Pizza',
    value: 'pizza',
    source: require('../assets/images/cuisines/pizza.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Portuguese',
    value: 'portuguese',
    source: require('../assets/images/cuisines/portuguese.jpg'),
  },
  {
    title: 'Salad',
    value: 'salad',
    source: require('../assets/images/cuisines/salad.jpg'),
  },
  {
    title: 'Sandwiches',
    value: 'sandwiches',
    source: require('../assets/images/cuisines/sandwiches.jpg'),
  },
  {
    title: 'Seafood',
    value: 'seafood',
    source: require('../assets/images/cuisines/seafood.jpg'),
  },
  {
    title: 'Senegalese',
    value: 'senegalese',
    source: require('../assets/images/cuisines/senegalese.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Singaporean',
    value: 'singaporean',
    source: require('../assets/images/cuisines/singaporean.jpg'),
  },
  {
    title: 'South African',
    value: 'south-african',
    source: require('../assets/images/cuisines/south-african.jpg'),
  },
  {
    title: 'South American',
    value: 'south-american',
    source: require('../assets/images/cuisines/south-american.jpg'),
  },
  {
    title: 'Sri Lankan',
    value: 'sri lankan',
    source: require('../assets/images/cuisines/sri-lankan.jpg'),
  },
  {
    title: 'Steak',
    value: 'steak',
    source: require('../assets/images/cuisines/steak.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Street Food',
    value: 'street-food',
    source: require('../assets/images/cuisines/street-food.jpg'),
  },
  {
    title: 'Sushi',
    value: 'sushi',
    source: require('../assets/images/cuisines/sushi.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Taiwanese',
    value: 'taiwanese',
    source: require('../assets/images/cuisines/taiwanese.jpg'),
  },
  {
    title: 'Thai',
    value: 'thai',
    source: require('../assets/images/cuisines/thai.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Tibetan',
    value: 'tibetan',
    source: require('../assets/images/cuisines/tibetan.jpg'),
  },
  {
    title: 'Turkish',
    value: 'turkish',
    source: require('../assets/images/cuisines/turkish.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Vietnamese',
    value: 'vietnamese',
    source: require('../assets/images/cuisines/vietnamese.jpg'),
  },
  {
    title: 'Uyghur',
    value: 'uyghur',
    source: require('../assets/images/cuisines/uyghur.jpg'),
    showOnOnboarding: true,
  },
  {
    title: 'Yemeni',
    value: 'yemeni',
    source: require('../assets/images/cuisines/yemeni.jpg'),
  },
];

export default CUISINES;
